### ISSUE TITLE
Throw error if not in project folder

### ISSUE THREAD

**Issue by ritz078** [jonschlinkert/load-pkg#1]
If we use this outside a project folder it should send `err` in callback so that I can handle it gracefully. currently it throws the following error on its own.

```
fs.js:303
  binding.open(pathModule._makeLong(path),
          ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readFile (fs.js:303:11)
    at /Users/ritz078/projects/starring/node_modules/load-pkg/index.js:26:8
    at /Users/ritz078/projects/starring/node_modules/find-file-up/index.js:50:9
    at /Users/ritz078/projects/starring/node_modules/find-file-up/index.js:93:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by jonschlinkert** [comment]
hmm, seems like the error is handled [properly in the callback here](https://github.com/jonschlinkert/load-pkg/blob/master/index.js#L24-L27), but I think I know where the issue is happening. I'll look into it and report back, thanks for creating the issue

**Comment by doowb** [comment]
@ritz078 this module has been refactored and will check if the package path was found before attempting to read in the `package.json`. If it's not found, then `undefined` is returned from `load-pkg`.

I'm going to close since it looks like this issue is solved in the newer version. Feel free to re-open this issue or open another one if you're still having problems.
